name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - project-template-esp32.yaml
          - project-template-esp8266.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@main
        with:
          yaml_file: ${{ matrix.file }}
